In [1]:
import numpy as np
import pandas as pd
import scipy.stats as st

In [6]:
N = 30
M = 3
np.random.seed(0)
mus = np.array([-1.0, 0.0, 1.0])
Xtrain = np.random.normal(loc=mus, scale=np.ones(M), size=(N, M))
Xtest = np.random.normal(loc=mus, scale=np.ones(M), size=(N, M))
print(mus)
print(Xtrain.shape)
print(Xtest.shape)

[-1.  0.  1.]
(30, 3)
(30, 3)


In [12]:
xm = Xtrain.mean(axis=0)
xm

array([-0.87033713,  0.13895062,  0.75100011])

In [14]:
xm + (1 - (M - 2) / np.power(Xtrain - xm, 2).sum(axis=0))()

array([-0.89691807,  0.1038967 ,  0.71283335])

In [19]:
415/1436

0.2889972144846797